[package]
name = "qr-issuer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
base64 = "0.22.1"
hmac = "0.12.1"
image = "0.25.2"
qrcode = "0.14.1"
qr-common = { path = "../qr-common" }
base85 = "2.0.0"
serde = { version = "1.0.209", features = ["derive"] }
